# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: event.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65vent.proto\"\xb3\x01\n\x05\x45vent\x12\x0f\n\x07\x65ventId\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x11\n\teventType\x18\x04 \x01(\t\x12\x14\n\x0c\x63\x61tegoryType\x18\x05 \x01(\t\x12\x15\n\rorganizerName\x18\x06 \x01(\t\x12\x11\n\tstartDate\x18\x07 \x01(\t\x12\x0f\n\x07\x65ndDate\x18\x08 \x01(\t\x12\x11\n\tbannerUrl\x18\t \x01(\t\"\xa7\x01\n\nEventInput\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x11\n\teventType\x18\x03 \x01(\t\x12\x14\n\x0c\x63\x61tegoryType\x18\x04 \x01(\t\x12\x15\n\rorganizerName\x18\x05 \x01(\t\x12\x11\n\tstartDate\x18\x06 \x01(\t\x12\x0f\n\x07\x65ndDate\x18\x07 \x01(\t\x12\x11\n\tbannerUrl\x18\x08 \x01(\t\"$\n\nEventsList\x12\x16\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x06.EventB\"\n\x14\x63om.bookmyshow.protoB\nEventProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.bookmyshow.protoB\nEventProto'
  _globals['_EVENT']._serialized_start=16
  _globals['_EVENT']._serialized_end=195
  _globals['_EVENTINPUT']._serialized_start=198
  _globals['_EVENTINPUT']._serialized_end=365
  _globals['_EVENTSLIST']._serialized_start=367
  _globals['_EVENTSLIST']._serialized_end=403
# @@protoc_insertion_point(module_scope)
