# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: movie.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'movie.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmovie.proto\"\xbe\x01\n\x05Movie\x12\x0f\n\x07movieId\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05genre\x18\x04 \x03(\t\x12\x14\n\x0c\x64urationMins\x18\x05 \x01(\x05\x12\x13\n\x0breleaseDate\x18\x06 \x01(\t\x12\x0e\n\x06rating\x18\x07 \x01(\x01\x12\x11\n\tlanguages\x18\x08 \x03(\t\x12\x10\n\x08imageKey\x18\t \x01(\t\x12\x11\n\tposterKey\x18\n \x01(\t\"\xb2\x01\n\nMovieInput\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\r\n\x05genre\x18\x03 \x03(\t\x12\x14\n\x0c\x64urationMins\x18\x04 \x01(\x05\x12\x13\n\x0breleaseDate\x18\x05 \x01(\t\x12\x0e\n\x06rating\x18\x06 \x01(\x01\x12\x11\n\tlanguages\x18\x07 \x03(\t\x12\x10\n\x08imageKey\x18\x08 \x01(\t\x12\x11\n\tposterKey\x18\t \x01(\t\"$\n\nMoviesList\x12\x16\n\x06movies\x18\x01 \x03(\x0b\x32\x06.MovieB\"\n\x14\x63om.bookmyshow.protoB\nMovieProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'movie_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.bookmyshow.protoB\nMovieProto'
  _globals['_MOVIE']._serialized_start=16
  _globals['_MOVIE']._serialized_end=206
  _globals['_MOVIEINPUT']._serialized_start=209
  _globals['_MOVIEINPUT']._serialized_end=387
  _globals['_MOVIESLIST']._serialized_start=389
  _globals['_MOVIESLIST']._serialized_end=425
# @@protoc_insertion_point(module_scope)
