# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: showtime.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'showtime.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eshowtime.proto\"\x7f\n\x08Showtime\x12\x12\n\nshowtimeId\x18\x01 \x01(\t\x12\x0f\n\x07venueId\x18\x02 \x01(\t\x12\x0f\n\x07movieId\x18\x03 \x01(\t\x12\x0f\n\x07\x65ventId\x18\x04 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x05 \x01(\t\x12\x0f\n\x07startAt\x18\x06 \x01(\t\x12\r\n\x05\x65ndAt\x18\x07 \x01(\t\"a\n\rShowtimeInput\x12\x0f\n\x07venueId\x18\x01 \x01(\t\x12\x0f\n\x07movieId\x18\x02 \x01(\t\x12\x0f\n\x07\x65ventId\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t\x12\x0f\n\x07startAt\x18\x05 \x01(\t\"E\n\x0fShowtimeDetails\x12\x12\n\nshowtimeId\x18\x01 \x01(\t\x12\x0f\n\x07startAt\x18\x02 \x01(\t\x12\r\n\x05\x65ndAt\x18\x03 \x01(\t\"\x8c\x01\n\x15ShowtimeMovieResponse\x12\x0f\n\x07venueId\x18\x01 \x01(\t\x12\x11\n\tvenueName\x18\x02 \x01(\t\x12\x13\n\x0bvenueMapUrl\x18\x03 \x01(\t\x12\x15\n\rvenueLocation\x18\x04 \x01(\t\x12#\n\tshowtimes\x18\x05 \x03(\x0b\x32\x10.ShowtimeDetails\"\xa7\x02\n\x16ShowtimeDetailResponse\x12\x1b\n\x08showtime\x18\x01 \x01(\x0b\x32\t.Showtime\x12\x11\n\tmovieName\x18\x02 \x01(\t\x12\x18\n\x10movieDescription\x18\x03 \x01(\t\x12\x15\n\rmovieImageUrl\x18\x04 \x01(\t\x12\x16\n\x0emoviePosterUrl\x18\x05 \x01(\t\x12\x15\n\rmovieDuration\x18\x06 \x01(\t\x12\x15\n\rmovieLanguage\x18\x07 \x01(\t\x12\x12\n\nmovieGenre\x18\x08 \x01(\t\x12\x11\n\tvenueName\x18\t \x01(\t\x12\x15\n\rvenueLocation\x18\n \x01(\t\x12\x13\n\x0bvenueMapUrl\x18\x0b \x01(\t\x12\x13\n\x0bmovieRating\x18\x0c \x01(\t\"F\n\x19ShowtimeMovieResponseList\x12)\n\tresponses\x18\x01 \x03(\x0b\x32\x16.ShowtimeMovieResponse\",\n\x0cShowtimeList\x12\x1c\n\tshowtimes\x18\x01 \x03(\x0b\x32\t.Showtime\"\x1c\n\x05Seats\x12\x13\n\x0b\x62ookedSeats\x18\x01 \x03(\tB%\n\x14\x63om.bookmyshow.protoB\rShowtimeProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'showtime_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.bookmyshow.protoB\rShowtimeProto'
  _globals['_SHOWTIME']._serialized_start=18
  _globals['_SHOWTIME']._serialized_end=145
  _globals['_SHOWTIMEINPUT']._serialized_start=147
  _globals['_SHOWTIMEINPUT']._serialized_end=244
  _globals['_SHOWTIMEDETAILS']._serialized_start=246
  _globals['_SHOWTIMEDETAILS']._serialized_end=315
  _globals['_SHOWTIMEMOVIERESPONSE']._serialized_start=318
  _globals['_SHOWTIMEMOVIERESPONSE']._serialized_end=458
  _globals['_SHOWTIMEDETAILRESPONSE']._serialized_start=461
  _globals['_SHOWTIMEDETAILRESPONSE']._serialized_end=756
  _globals['_SHOWTIMEMOVIERESPONSELIST']._serialized_start=758
  _globals['_SHOWTIMEMOVIERESPONSELIST']._serialized_end=828
  _globals['_SHOWTIMELIST']._serialized_start=830
  _globals['_SHOWTIMELIST']._serialized_end=874
  _globals['_SEATS']._serialized_start=876
  _globals['_SEATS']._serialized_end=904
# @@protoc_insertion_point(module_scope)
